### ISSUE TITLE
Set up directory structure

### ISSUE THREAD

**Issue by amondal2** [CDCgov/cfa-config-generator#1]
Set up directories to hold config-generating scripts. I think we should do this in a way that we can add more pipelines later on without too much trouble, but have some shared utils and Azure management stuff. Maybe something like:
```
pipelines/
    epinow2/
    <other models>/ 
    ....
utils/
    azure/
        storage.py
        auth.py
        ...
```
@natemcintosh @zsusswein what do you two think?

**Comment by natemcintosh** [comment]
I really like it! That `utils` folder in particular will be useful.

**Comment by zsusswein** [comment]
Look good!
