### ISSUE TITLE
QOL Improvement: change run_id placement in name

### ISSUE THREAD

**Issue by natemcintosh** [CDCgov/cfa-config-generator#27]
## Goal
Make configs in the `rt-epinow2-config` storage container slightly easier to work with.

## Context
At the moment, each top level folder has the name pattern: `Rt-estimation-<long_run_id>-<timestamp>`.

I propose altering it to be `Rt-estimation-<timestamp>-<long_run_id>`, entirely for the purpose of being able to sort by the folder name, and get the most recently created ones.

**Comment by amondal2** [comment]
Will do @natemcintosh!
