### ISSUE TITLE
Add bulk update of config objects

### ISSUE THREAD

**Issue by amondal2** [CDCgov/cfa-config-generator#35]
We should add functionality to update all config objects within a given job. @natemcintosh @zsusswein could you remind me which config fields this should apply to?

**Comment by natemcintosh** [comment]
I *think* everything in the `modifiable_params`

https://github.com/CDCgov/cfa-config-generator/blob/95bccc1d3b9351ce20a5a49c16483076f315b7d9/utils/epinow2/constants.py#L85

**Comment by amondal2** [comment]
@natemcintosh any thoughts on how to handle nested dictionaries? I guess we could specify the key explicitly, eg. `confmod bulk-update --job-id <job-id> --key 'priors.rt.mean' --value 1.5` but that seems kind of clunky

**Comment by natemcintosh** [comment]
Is it possible to do it the same way as in the regular update? Where it interactively asks you what you want to update, and if it's a nested item, then recurse?

**Comment by amondal2** [comment]
Yeah, I think that should work. Will give it a shot - thanks!
