### ISSUE TITLE
Make job_id user configurable 

### ISSUE THREAD

**Issue by amondal2** [CDCgov/cfa-config-generator#37]
If the config generation is being handled by an upstream script in the epinow2-pipeline repo, then the job_id should be generated there and passed to this service. Currently, the job_id is generated here.

**Comment by amondal2** [comment]
@natemcintosh @zsusswein the only issue I see is that `task_ids` currently assume that the `job_id` includes a UUID hex. Do we need this in the task_ids? If not, then we can do `<state>_<disease>_<timestamp>.json` and the `job_id` will be a field in the task instead of in the name.

**Comment by natemcintosh** [comment]
I don't see any current technical issues with removing the UUID. (It would certainly make reading them easier).
