### ISSUE TITLE
Push configs to Azure Blob Storage

### ISSUE THREAD

**Issue by amondal2** [CDCgov/cfa-config-generator#5]
Once config JSONs have been generated, they should be pushed to ABS. I am thinking we can create a new bucket that just stores the config files; something like `epinow2-config/` but I'm open to suggestions on the name.

These configs will either be generated on a schedule or by a user-triggered function. My thought is that the code in this repo should only handle generating _new_ jobs, whereas the CLI tool we'll build later will handle modifying _existing_ jobs. To distinguish between the two, we can timestamp the task_ids (or use metadata to pull the latest written task), something like:

```
epinow2-config/
    <job_id>/ 
           <task1_id_timestamp1>.json
           <task2_id_timestamp1>.json
           <task1_id_timestamp2>.json
   <job_id>/
```

Or we can split them into different directories and pull the latest downstream:
```
epinow2-config/
    <job_id>/ 
        initial/
           <task1_id>.json
           <task2_id>.json
           ....
        modified/ 
           <task1_id>.json
           <task2_id>.json
            ....
   <job_id>/
```

I'm open to either, let me know what makes more sense given your workflows. @zsusswein @natemcintosh @PatrickTCorbett

**Comment by zsusswein** [comment]
Strong preference for the former! I think we want to avoid assumptions around jobs and numbers of runs or modifications.

Will write more about this in the postprocessing thing, but I'd pitch the CLI tool and the code here are both agnostic to whether the run is a re-run or an initial run. My ideal would be that the CLI provide additional fine-grained control around generating the configs, but would lead to an identical path structure.

**Comment by amondal2** [comment]
Sounds good @zsusswein

**Comment by natemcintosh** [comment]
I think it would be nice if we had a single tool for generating and modifying the configs. What if this repo is the CLI tool, and we have some CI here that calls it to generate the default/scheduled configs?

I also agree that it would be good for the CLI to be agnostic about whether it's a re-run or initial run.

**Comment by amondal2** [comment]
That's a good idea @natemcintosh -- I think initially I thought having both in the same repo would get unwieldy, but there will be a lot of shared functionality/utils so we should probably just keep everything in one place. Let's sort out the scripts for default generation then we can add the CLI here 👍
