### ISSUE TITLE
Implement test suite

### ISSUE THREAD

**Issue by amondal2** [CDCgov/cfa-config-generator#9]
Implement a test suite that runs on PR CI to check that validation, argument sanitization, and task config generation are working as expected.

**Comment by zsusswein** [comment]
This would be wild overkill, but if you felt like figuring out how to implement an end-to-end test running in CI with `azurite` I would use it in other projects too. I wanted to do mocking for our ETL job with an azure version of `moto` but I couldn't find anything but `azurite` and it was complicated enough that I didn't try it out.
